export interface AdminUserConfig {
  UserType: string;
  MenuItems: MenuModel[];
  AllowLicenses: boolean;
  AllowScheduledReminderEmail: boolean;
  IsMVP: boolean;
  AssociatedTenants: TenantViewModel[];
  ShowAssociatedTenants: boolean;
  SelectedTenant: TenantViewModel;
  AllowCSPLicense: boolean;
  AllowHotInstance: boolean;
  EnableAWS: boolean;
  EnableGCP: boolean;
  EnableRequesterTagging: boolean;
  AllowTestDrive: boolean;
  LastUsedFilter: number;
  AllowEvent: boolean;
  DefaultNavigation: string;
  AllowAzurePass: boolean;
  AllowPrivateSubscriptions: boolean;
  AllowTemplateSharing: boolean;
  EncryptedAttendee: EncryptedAttendeeModel;
  AllowCostEstimate: boolean;
  TenantAllowShowingInCloudLabs: boolean;
  AllowInstructorLogin: boolean;
  ComputeVMUsage: boolean;
  EnableAccessOverHttp: boolean;
  IsAcceptedEmail: boolean;
  EnableSnapshot: boolean;
  EnableODLSurvey: boolean;
  AllowBlockingOfUser: boolean;
  AllowUserMaxRetakeCount: boolean;
  AllowUserToSelectRegion: boolean;
  AllowLabClusters: boolean;
  AllowOdlLevelLabguide: boolean;
  AllowConnectChannel: boolean;
  EnableInstructorPermissionsToODL: boolean;
  AllowCloneODL: boolean;
  AllowUserToExtendLab: boolean;
  EnableHotInstanceCleanUp: boolean;
  EnableCustomLabDetailsPage: boolean;
  AllowSystemIntegration: boolean;
  EnableAttendeeTracking: boolean;
  EnableLabCostAlerts: boolean;
  AllowSampleLabRequestODL: boolean;
  ShowLabRequestUniqueId: boolean;
  AllowMaximumAllowedDuration: boolean;
  EnableAutoOrganization: boolean;
  EnableManagePortal: boolean;
  EnableBannerImage: boolean;
  CustomStudentPortalURL: string;
  EnableTeamsChannel?: boolean;
  EnableHackathon: boolean;
  PartnerUserEmail: string;
  EnableInstructorToEditODL: boolean;
  DefaultScheduleMaxretryCount?: number;
  AllowEnvironmentDeleteNotification: boolean;
  AllowLabRequestIncidents: boolean;
  EnableAutoLabValidation: boolean;
  EnableResourceIdlenessMonitoring: boolean;
  EnablePowershellModulesToInstall?: boolean;
  EnableInstructorToAddActivationCode: boolean;
  AllowAutomaticDeploymentReadyForInstructor: boolean;
  EnableManualStatusChange: boolean;
  EnableAIWEventCreation: boolean;
  EnableLabDurationAlgorithm: boolean;
  EnableCustomerName: boolean;
  EnableCreditBasedAllocation: boolean;
  CreditLimit?: number;
  IsSupportQuest: boolean;
  SysAdminAllowEventCreation: boolean;
  MakeLabRequestUniqueIdOptional: boolean;
  RequestBufferPeriod?: number;
  SubPartnerId?: number;
  HasOngoingLearning: boolean;
  EnableVoucherRetake: boolean;
  EnableLTIConfiguration: boolean;
  ODLTitleFormat: string;
  EnableLabDeletionAlert: boolean;
  BlockAutomatedEmailsToInstructor: boolean;
  AttendeeEndDate: boolean;
  EnableProfileSettingForTestDrive: boolean;
  GrantAttendeeAccesstoCLPortal: boolean;
  AllowODLUniqueNameUpdate: boolean;
  DisableSyncWithCloud: boolean;
  EnableWallpaperRDPoverHTTPS: boolean;
  EnablePeriodicUptime: boolean;
  EnableSalesTeamCommunication: boolean;
  AutoAddInstructors: boolean;
  DefaultLimitedAccess: boolean;
  DayOrWeekValidation?: number;
  EnablePartnerProgram?: boolean;
  EnableLabAssets: boolean;
  AllowReadonlyODLAccessToInstructor: boolean;
  LogoInstructions: string;
  EnableHealthCheck: boolean;
  EnableAllocateDome9Account?: boolean;
  CLPortalURL: string;
  EnableCatalogBadge: boolean;
  ExcludedOutputParameters: string;
}

export interface TenantViewModel {
  Name: string;
  Id: number;
  UserId: number;
  Email: string;
  PartnerProfile: PartnerProfile;
  RoleName: string;
  RoleId: number;
  InternalPartnerId: string;
  InternalRoleId: string;
  UniqueName: string | null;
  AllowPrivateSubscriptions: boolean;
}

export interface MenuModel {
  Text: string;
  Sref: string;
  Icon: string;
  ReportsSubMenuText: string;
  ReportsSubMenuSref: string;
  SubMenu: MenuModel[];
  Order?: number;
}

export interface EncryptedAttendeeModel {
  InternalId: string;
  OrganizationInternalId: string;
  IsOrganizationAdmin: boolean;
}

export interface PartnerProfile {
  Id: number;
  EncryptedPartnerId: string;
  LogoUrl: string;
  Name: string;
  PartnerUrl: string;
  Description: string;
  PrimaryDomainName: string;
  TenantId: string;
  Specialization: string;
  AddressLine1: string;
  AddressLine2: string | null;
  City: string | null;
  State: string;
  Country: string;
  Zip: string | null;
  AllowCustomSubscriptionGroup: boolean;
  AllowLicenses: boolean;
  AllowScheduledReminderEmail: boolean;
  IsMVP: boolean;
  AllowTestDrives: boolean;
  AllowWebinars: boolean;
  AllowSummaryEmail: boolean;
  AllowInstructorLogin: boolean;
  CustomPrivacyUrl: string | null;
  CustomPrivacyStatement: string | null;
  PartnerBannerText: string | null;
  AllowCSPLicense: boolean;
  AllowHotInstance: boolean;
  PublicName: string;
  EnableAWS: boolean;
  EnableGCP: boolean;
  EnableCalendar: boolean;
  ShowHelpMenu: boolean;
  AllowEvent: boolean;
  RequesterRegex: string | null;
  MaxConcurrentTestDrives: number;
  SupportBridgeUrl: string;
  SupportEmail: string | null;
  InviteEmailSendBefore: string | null;
  EnableRequesterTagging: boolean;
  AllowAzurePass: boolean;
  AllowPrivateSubscriptions: boolean;
  AllowTemplateSharing: boolean;
  AllowCostEstimate: boolean;
  AllowShowingInCloudlabs: boolean;
  LabPromotionMessage: string;
  ComputeVMUsage: boolean;
  EnableAccessOverHttp: boolean;
  EnablePowershellModules: boolean;
  EnableSnapshot: boolean;
  EnableODLSurvey: boolean;
  AutoAddInstructors: boolean;
  SignUpSupportInfoEmailTemplate: string;
  AllowBlockingOfUser: boolean;
  Clusters: Cluster[];
  CommunicationEmailTitle: string | null;
  AllowUserMaxRetakeCount: boolean;
  AllowOdlLevelLabguide: boolean;
  AllowUserToSelectRegion: boolean;
  EnableInstructorPermissionsToODL: boolean;
  AllowConnectChannel: boolean;
  AllowCloneODL: boolean;
  AllowUserToExtendLab: boolean;
  EnableHotInstanceCleanUp: boolean;
  EnableCustomLabDetailsPage: boolean;
  AllowSystemIntegration: boolean;
  EnableAttendeeTracking: boolean;
  EnableLabCostAlerts: boolean;
  AllowSampleLabRequestODL: boolean;
  IsDataAnonymizationEnabled: boolean;
  ShowLabRequestUniqueId: boolean;
  AllowMaximumAllowedDuration: boolean;
  EnableAutoOrganization: boolean;
  EnableManagePortal: boolean;
  DefaultLimitedAccess: boolean;
  PartnerHeaderLogo: string;
  ThemeId: number;
  PartnerBannerImage: string;
  CustomStudentPortalURL: string | null;
  EnableTeamsChannel: boolean;
  EnableHackathon: boolean;
  EnableInstructorCommunicationInfo: boolean;
  EnableReduceExpectedAttendeeCount: boolean;
  EnableInstructorCloudCredentialLogin: boolean;
  EnableInstructorToEditODL: boolean;
  DefaultScheduleMaxretryCount: number | null;
  NotificationEmail: string | null;
  TermsofUseURL: string | null;
  AllowEnvironmentDeleteNotification: boolean;
  EnableAutoHotInstanceEmailForLabRequest: boolean;
  EnableAutoLabValidation: boolean;
  EnableResourceIdlenessMonitoring: boolean;
  EnableInstructorToAddActivationCode: boolean;
  BlockAutomatedEmailsToInstructor: boolean;
  AllowAutomaticDeploymentReadyForInstructor: boolean;
  EnableManualStatusChange: boolean;
  EnableLabDurationAlgorithm: boolean;
  EnableCustomerName: boolean;
  EnableCreditBasedAllocation: boolean;
  CreditLimit: number | null;
  IsSupportQuest: boolean;
  CETenantUniqueName: string;
  CEChannelUniqueName: string;
  EnableVoucherRetake: boolean;
  EnableLTIConfiguration: boolean;
  ODLTitleFormat: string;
  PartnerFromEmailAddress: string | null;
  CustomTransparentLogo: string;
  TrialAppURL: string | null;
  PartnerConsumerAssociations: any[];
  EnableLabDeletionAlert: boolean;
  AttendeeEndDate: boolean;
  EnableCustomFooter: boolean;
  EnableProfileSettingForTestDrive: boolean;
  GrantAttendeeAccesstoCLPortal: boolean;
  AllowODLUniqueNameUpdate: boolean;
  DisableSyncWithCloud: boolean;
  EnableWallpaperRDPoverHTTPS: boolean;
  EnablePeriodicUptime: boolean;
  AllowEventCreation: boolean;
  RequestBufferPeriod: number;
  EmailSender: string | null;
  EnableSalesTeamCommunication: boolean;
  RestrictLabRequestUpdateAlgo: number;
  DaysToRestrictLabRequestUpdate: number;
  EnablePartnerProgram: boolean;
  EnableLabAssets: boolean;
  FaviconUrl: string | null;
  AllowReadonlyODLAccessToInstructor: boolean;
  IsAlreadyUnsubscribe: boolean;
  ContactUsURL: string | null;
  MakeLabRequestUniqueIdOptional: boolean;
  EnableHealthCheck: boolean;
  EnableAllocateDome9Account: boolean;
  EnableCatalogBadge: boolean;
  SendCreditAlertToNotificationAddress: boolean;
  ExcludedOutputParameters: any | null;
  EnableLaaS: boolean;
}

export interface Cluster {
  ClusterId: number;
  ClusterName: string;
  ClusterTypeId: number;
}
